name: Sutil Tests
on: [push, workflow_dispatch]
jobs:
  Run-Sutil-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Clean
        run: |
          cd ${{ github.workspace }}
          dotnet clean src/Sutil && dotnet nuget locals all --clear
          dotnet clean src/App && dotnet nuget locals all --clear
          dotnet clean src/DevTools && dotnet nuget locals all --clear
          dotnet clean tests/test && dotnet nuget locals all --clear
          dotnet clean tests/src/Fable.Expect && dotnet nuget locals all --clear
      - name: Install dotnet tools
        run: |
          cd ${{ github.workspace }}/tests
          pwd
          npm install
      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          npm run test
      - run: echo "🍏 This job's status is ${{ job.status }}."
