name: Sutil Test Commit
on: [workflow_dispatch]
jobs:
  Sutil-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Fake edit
        run: |
          echo "- Testing Commits from GH actions" >> TODO.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: TODO.md
          commit_message: Apply php-cs-fixer changes
